CREATE DATABASE EJER11
GO 
USE EJER11
GO 
CREATE TABLE NIVEL(
IDNIVEL SMALLINT PRIMARY KEY CHECK (IDNIVEL = 1 OR IDNIVEL = 2 OR IDNIVEL = 3 OR IDNIVEL = 4),
NOMBRE VARCHAR (11) NOT NULL
)
GO 
CREATE TABLE CARRERAS (
IDCARRERA VARCHAR (4) PRIMARY KEY, 
NOMBRE VARCHAR (12) NOT NULL,
FECHA_CREACION DATE NOT NULL CHECK (FECHA_CREACION <GETDATE()),
MAIL VARCHAR (20) NOT NULL, 
IDNIVEL SMALLINT NOT NULL  FOREIGN KEY REFERENCES NIVEL (IDNIVEL)
)
GO 
CREATE TABLE MATERIAS (
IDMATERIAS INT NOT NULL PRIMARY KEY IDENTITY (1,1), 
IDCARRERA VARCHAR (4) NOT NULL FOREIGN KEY REFERENCES CARRERAS (IDCARRERA), 
NOMBRE VARCHAR (12) NOT NULL,
CARGA_HORARIA SMALLINT NOT NULL CHECK (CARGA_HORARIA >0)
)
GO 
CREATE TABLE ALUMNOS (
LEGAJO BIGINT NOT NULL PRIMARY KEY IDENTITY (1000, 1), 
IDCARRERA VARCHAR (4) NOT NULL FOREIGN KEY REFERENCES CARRERAS (IDCARRERA),
NOMBRE VARCHAR (12) NOT NULL, 
APELLIDO VARCHAR (12) NOT NULL, 
FECHA_NACIMIENTO DATE NOT NULL CHECK (FECHA_NACIMIENTO < GETDATE ()), 
MAIL VARCHAR (20) NOT NULL, 
TELEFENO VARCHAR (20) NULL
)