CREATE DATABASE EJERCICIO_CARPINTERIA_13
GO 
USE EJERCICIO_CARPINTERIA_13
GO 
CREATE TABLE CATEGORIAS(
	IDCATEGORIA INT NOT NULL PRIMARY KEY IDENTITY (1,1), 
	NOMBRE VARCHAR (100) NOT NULL UNIQUE
)
GO
CREATE TABLE CLIENTES (
	IDCLIENTE INT NOT NULL PRIMARY KEY, 
	APELLIDO VARCHAR (50) NOT NULL, 
	NOMBRE VARCHAR (50) NOT NULL,
	FECHA_NACIMIENTO DATE NULL, 
	EMAIL VARCHAR (50) NULL, 
	TELEFONO VARCHAR (50) NULL, 
	CELULAR VARCHAR (50) NULL, 
	REGISTROWEB BIT NOT NULL
)
GO
CREATE TABLE PRODUCTOS(
	IDPRODUCTO INT NOT NULL PRIMARY KEY, 
	IDCATEGORIA INT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS (IDCATEGORIA),
	DESCRIPCION VARCHAR (100) NOT NULL, 
	PRECIO_VENTA MONEY NOT NULL, 
	PRECIO_MAYORISTA MONEY NOT NULL,
	CANTIDAD_MAYORISTA TINYINT NOT NULL, 
	COSTO MONEY NOT NULL, 
	DIAS_DE_CONSTRUCCION TINYINT NOT NULL
)
GO 
CREATE TABLE PEDIDOS (
	IDPEDIDO BIGINT NOT NULL PRIMARY KEY IDENTITY(1000,1),
	IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(IDPRODUCTO),
	CANTIDAD SMALLINT NOT NULL,
	IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES (IDCLIENTE),
	FECHA_SOLICITUD DATE NOT NULL,
	FECHA_FINALIZACION DATE NULL, 
	COSTO MONEY NOT NULL, 
	ABONADO BIT NOT NULL
)
GO 
CREATE TABLE COLABORADORES (
	LEGAJO INT NOT NULL PRIMARY KEY, 
	APELLIDO VARCHAR (50) NOT NULL,
	NOMBRE VARCHAR (50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	MODALIDAD CHAR(1) NOT NULL CHECK (MODALIDAD IN ('F','P')),
	SUELDO MONEY NOT NULL,
	AÑO_INGRESO SMALLINT NOT NULL
)