CREATE DATABASE Ejercicio1A
GO 
USE Ejercicio1A
GO 
CREATE TABLE PROVINCIAS(
IDPROVINCIA SMALLINT NOT NULL PRIMARY KEY,
PROVINCIAS VARCHAR (50) NOT NULL
)
GO 
CREATE TABLE LOCALIDADES (
CP INT NOT NULL PRIMARY KEY, 
IDPROVINCIA SMALLINT NOT NULL FOREIGN KEY REFERENCES PROVINCIAS (IDPROVINCIA),
LOCALIDAD VARCHAR (12) NOT NULL, 
)

GO 
CREATE TABLE VENDEDORES (
LEGAJO INT PRIMARY KEY NOT NULL, 
DNI INT UNIQUE NOT NULL, 
NOMBRE VARCHAR (12) NOT NULL, 
APELLIDO VARCHAR (12) NOT NULL, 
SEXO VARCHAR (1) CHECK (SEXO = 'M' OR SEXO= 'F'),
FECHA_NACIMIENTO DATE NOT NULL, 
FECHA_INGRESO DATE NOT NULL, 
SUELDO SMALLMONEY NOT NULL,
CP INT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES (CP)
)
GO 
CREATE TABLE CLIENTES (
DNI INT NOT NULL PRIMARY KEY, 
NOMBRE VARCHAR (12) NOT NULL, 
APELLIDO VARCHAR (12) NOT NULL, 
SEXO VARCHAR (1) NULL CHECK (SEXO = 'M' OR SEXO = 'F'), 
TELEFONO VARCHAR (20) NOT NULL, 
EMAIL VARCHAR (50) NOT NULL, 
FECHA_ALTA DATE NOT NULL, 
FECHA_NACIMIENTO DATE NOT NULL, 
DIRECCION VARCHAR (50) NOT NULL, 
CP INT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES (CP)
)
GO 
CREATE TABLE MARCAS (
 IDMARCA INT NOT NULL PRIMARY KEY, 
 MARCA VARCHAR (12) NOT NULL, 
)
GO 
CREATE TABLE TIPO_ARTICULOS(
IDTIPOARTICULO INT NOT NULL PRIMARY KEY, 
TIPO_ARTICULO VARCHAR (20) NOT NULL
)
GO 
CREATE TABLE ARTICULOS (
CODIGO_ARTICULO VARCHAR (6) NOT NULL PRIMARY KEY, 
DESCRIPCION VARCHAR (100) NULL, 
IDMARCA INT NOT NULL FOREIGN KEY REFERENCES MARCAS (IDMARCA),
IDTIPOARTICULO INT NOT NULL FOREIGN KEY REFERENCES TIPO_ARTICULOS (IDTIPOARTICULO),
PRECIO_COMPRA SMALLMONEY NOT NULL, 
PRECIO_VENTA SMALLMONEY NOT NULL, 
STOCK SMALLINT NOT NULL,
STOCK_MINIMO SMALLINT NOT NULL,
ESTADO BIT NOT NULL
)
GO 
CREATE TABLE DETALLE_X_VENTA (
NUMERO_VENTA BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1), 
DNI_CLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(DNI),
VENDEDOR INT NOT NULL FOREIGN KEY REFERENCES VENDEDORES (LEGAJO),
FORMA_PAGO CHAR (1) NOT NULL CHECK (FORMA_PAGO = 'T' OR FORMA_PAGO = 'E'), 
IMPORTE MONEY NOT NULL
)
GO
CREATE TABLE ARTICULOS_X_VENTA (
NUMERO_VENTA BIGINT NOT NULL FOREIGN KEY REFERENCES DETALLE_X_VENTA (NUMERO_VENTA), 
CODIGO_ARTICULO VARCHAR (6) NOT NULL FOREIGN KEY REFERENCES ARTICULOS (CODIGO_ARTICULO),
PRECIO MONEY NOT NULL, 
CANTIDAD SMALLINT NOT NULL
)